version: '3.8'

services:
  video-processing:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspace
    environment:
        - DISPLAY=host.docker.internal:0
        - QT_X11_NO_MITSHM=1
        - PYTHONPATH=/workspace
        - PYTHONDONTWRITEBYTECODE=1
        - PYTHONUNBUFFERED=1
            
    working_dir: /workspace
    # Keep the container running
    tty: true
    # Enable interactive mode
    stdin_open: true
    # For GUI applications and webcam access (if needed)
    #devices:
   #   - /dev/video0:/dev/video0
    # For better performance with OpenCV
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 4G
        reservations:
          cpus: '2'
          memory: 2G
    # Add network configuration for potential future web services
    networks:
      - video-processing-network

networks:
  video-processing-network:
    driver: bridge
