version: '3.8'

services:
  # Existing video processing container
  video-processing:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspace
    environment:
      - DISPLAY=host.docker.internal:0
      - QT_X11_NO_MITSHM=1
      - PYTHONPATH=/workspace
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    working_dir: /workspace
    tty: true
    stdin_open: true
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 4G
        reservations:
          cpus: '2'
          memory: 2G
    networks:
      - video-processing-network
    depends_on:
      - rtmp-server  # ensure RTMP server starts first

  # RTMP server for OBS streaming
  rtmp-server:
    image: alfg/nginx-rtmp
    ports:
      - "1935:1935"  # RTMP port for OBS stream
      - "8080:80"    # optional web UI to monitor streams
    networks:
      - video-processing-network

networks:
  video-processing-network:
    driver: bridge
